### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by tamnv** [propeoplemd/cibox#440]
I have error when I install CIBOX on ubuntu:

failed: [128.199.90.184] => (item=ansible==1.9.4) => {"cmd": "/usr/local/bin/pip install ansible==1.9.4", "failed": true, "item": "ansible==1.9.4"}
msg: 
:stderr: Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==8.1.1', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pip-8.1.1-py2.7.egg/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 579, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
===============
And I solve by these commands:
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
sudo dpkg-reconfigure locales

**Comment by podarok** [comment]
Thanks for reporting this

@tamnv what Ubuntu version are you using?

Looks like sort of limited/changed one

**Comment by tamnv** [comment]
Hi @podarok,

Ubuntu version: Ubuntu 14.04.4 LTS

**Comment by podarok** [comment]
@tamnv custom installed or provided by some hosting?

**Comment by tamnv** [comment]
@podarok I try to install to hosting provided by Digital Ocean.

**Comment by podarok** [comment]
heh, looks like a new bug according to .4 version.

**Comment by asgorobets** [comment]
I must mention that the locale was set on local ubuntu machine running ansible, not on ansible hosts. Maybe it's a specific Ubuntu settings causing it, the ansible was ran from a local ubuntu, not a digital ocean, DO was one of ansible hosts.

**Comment by podarok** [comment]
local machine should not break remote execution @asgorobets so looks like we need to address it anyway
We are doing provisioning from different hosts , like ubuntu, debian, osx, so if there is a state for ubuntu when provisioning fails - it is a bug
